In [2]:
'''
     Numpy通用函数

    基本操作
'''

'\n     Numpy通用函数\n\n    基本操作\n'

In [39]:
import numpy as np
# 数组形状：.T/.reshape()/.resize()
ar1 = np.arange(10)
print(ar1,ar1.shape)    
print('转置T后:',ar1.T)
    
# 必须保证秩一样
ar2_reshape = ar1.reshape(2,5)  #   用法1：直接将已有数组改变形状
ar3_reshape = np.reshape(ar1, (2,5))  # 用法2：参数内添加数组，目标形状
ar4_reshape = np.zeros((4,6)).reshape(3,8)  # 用法3：生成数组后直接改变形状
print('ar2_reshape  reshape()后:',ar2_reshape)
print('ar3_reshape  reshape()后:',ar3_reshape)
print('ar4_reshape  reshape()后:',ar4_reshape)
                         
ar1_resize = np.resize(ar1, 12)  # 不用保证秩一样 可以大于原来的
ar2_resize = np.resize(ar3_reshape, 5)  # 不用保证秩一样 可以小于原来的
print('ar4_resize resize()后:',ar1_resize)  # ar1_resize是新的数组
print('ar3_reshape resize()后:',ar2_resize)  # ar2_resize是新的数组  

n = np.arange(10)
p = np.arange(12)
print(np.resize(n, (2,6)))  # 输出结果正常  这种调用方式会生成一个新的数组
print(p.resize((3,4)))  # 输出结果为None  这种调用方式会改变数组本身,不会生成新的数组 看源码即可
print('n被改变了:', n)  # 结果显示n已经被改变了

[0 1 2 3 4 5 6 7 8 9] (10,)
转置T后: [0 1 2 3 4 5 6 7 8 9]
ar2_reshape  reshape()后: [[0 1 2 3 4]
 [5 6 7 8 9]]
ar3_reshape  reshape()后: [[0 1 2 3 4]
 [5 6 7 8 9]]
ar4_reshape  reshape()后: [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
ar4_resize resize()后: [0 1 2 3 4 5 6 7 8 9 0 1]
ar3_reshape resize()后: [0 1 2 3 4]
[[0 1 2 3 4 5]
 [6 7 8 9 0 1]]
None
n被改变了: [0 1 2 3 4 5 6 7 8 9]


In [29]:
# 数组的复制
ar1_denghao =  ar1
print(ar1_denghao)
print( ar1_denghao is ar1)
ar1[1] = 9
print(f'等号赋值结果,ar1={ar1},ar1_denghao={ar1_denghao}')
# 回忆python的赋值逻辑：指向内存中生成的一个值 → 这里ar1和ar1_denghao指向同一个值，所以ar1改变，ar1_denghao一起改变
print('------------------')

# .copy()则不同
ar1 = np.arange(10)
ar1_copy = ar1.copy()
print(ar1_copy)
print(ar1_copy is ar1)
ar1[1] = 9
print(f'copy()复制结果,ar1={ar1},ar1_copy={ar1_copy}')  # ar1_copy并未改变
# copy方法生成数组及其数据的完整拷贝
# 提醒：.T/.reshape()/.resize()都是生成新的数组！！！

[0 9 2 3 4 5 6 7 8 9]
True
等号赋值结果,ar1=[0 9 2 3 4 5 6 7 8 9],ar1_denghao=[0 9 2 3 4 5 6 7 8 9]
------------------
[0 1 2 3 4 5 6 7 8 9]
False
copy()复制结果,ar1=[0 9 2 3 4 5 6 7 8 9],ar1_copy=[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [44]:
# 数组类型转换：.astype()
ar1 = np.arange(10, dtype=float)
ar2 = ar1.astype(np.int64)
print(ar1,ar1.dtype)
print(ar2,ar2.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64
[0 1 2 3 4 5 6 7 8 9] int64


In [205]:
# 数组堆叠

a = np.arange(5)
b = np.arange(5,9)
print(a)
print(b)
print(np.hstack((a,b)))  # 横向连接 水平按列

a = np.array([[1],[2],[3]])
b = np.array([['a'],['b'],['c']])
print(a)
print(b)
print(np.hstack((a,b)))  # 横向连接 变成3行2列的数组
print(np.vstack((a,b)))  # 纵向连接 垂直按行 变成6行1列的数组, 但必须保证两个数组的秩一样

c = np.array(np.ones((3,2)))
d = np.array(np.zeros((2,2)))
print(d)
print(c)
# print(np.hstack((c,d)))  # 横向连接 行数必须保持一致
print(np.vstack((c,d)))  # 纵向连接 列数必须保持一致,否则会以下错误
'''
ValueError: all the input array dimensions except for the concatenation axis must match exactly
ValueError：除串联轴外的所有输入数组维必须完全匹配
'''

[0 1 2 3 4]
[5 6 7 8]
[0 1 2 3 4 5 6 7 8]
[[1]
 [2]
 [3]]
[['a']
 ['b']
 ['c']]
[['1' 'a']
 ['2' 'b']
 ['3' 'c']]
[['1']
 ['2']
 ['3']
 ['a']
 ['b']
 ['c']]
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]


'\nValueError: all the input array dimensions except for the concatenation axis must match exactly\nValueError：除串联轴外的所有输入数组维必须完全匹配\n'

In [204]:
# 数组拆分
ar = np.arange(start=1,stop=17).reshape(2,8)  
print(ar)
ar_hsp = np.hsplit(ar, [2,5,8])  
"""
按索引[2,5,8]垂直（行）将数组拆分为多个子数组。
可以理解为在数组的索引处划一刀(如切3刀分4块),然后在'缺口'那儿向上取'分块',已经取走的就不包含,
最后一个'缺口'需要特别注意:
    如果小于索引最大值,则依然向上取'分块'
    如果等于索引最大值,则取最大索引处的值
    如果大于索引最大值,则依然向上取'分块',但同时会向下取一个空数组,
    并且该数组的shape(n,0)和dtype会与上面的'分块'保持一致
"""
print('按索引拆,ar_hsp:', ar_hsp)
print('按索引拆,len():',len(ar_hsp))
ar_hsp = np.hsplit(ar, 2)  # 按节(8/2=4 ,每4个为一组)水平（按列））将数组拆分为多个子数组。
print('按节拆,type():',type(ar_hsp))
print('按节拆,len():',len(ar_hsp))
print('按节拆,ar_hsp:',ar_hsp)
print('按节拆,ar_hsp[0]:',ar_hsp[0])
'''
    hsplit等效于带有axis = 1的split，无论数组大小如何，数组总是沿第二个轴拆分。
'''
print('------------------------------')
ar =np.arange(start=1,stop=17).reshape(2,8)
print(ar)
ar_vsp = np.vsplit(ar, [2,5,8])  
"""
按索引[2,5,8]垂直（行）将数组拆分为多个子数组。
可以理解为在数组的索引处划一刀(如切3刀分4块),然后在'缺口'那儿向上取'分块',已经取走的就不包含,
最后一个'缺口'需要特别注意:
    如果小于索引最大值,则依然向上取'分块'
    如果等于索引最大值,则取最大索引处的值
    如果大于索引最大值,则依然向上取'分块',但同时会向下取一个空数组,
    并且该数组的shape(n,0)和dtype会与上面的'分块'保持一致
    如下面输出结果显示:array([], shape=(0, 8), dtype=int32
"""
print('按索引拆,ar_vsp:', ar_vsp)
print('按索引拆,len():',len(ar_vsp))
ar_vsp = np.vsplit(ar, 2)  # 按节(8/2=4 ,每4个为一组)垂直（行）将数组拆分为多个子数组。
print('按节拆,type():',type(ar_vsp))
print('按节拆,len():',len(ar_vsp))
print('按节拆,ar_vsp:',ar_vsp)
print('按节拆,ar_vsp[0]:',ar_vsp[0])

'''
vsplit等同于使用axis = 0的split（默认值），无论数组尺寸如何，数组始终沿第一个轴拆分

ar_vsp = np.vsplit(ar,5) # 报错

numpy.vsplit(ary, indices_or_sections)
注意点:
- 数组拆分必须是均分的,否则会报错
- 垂直（行）将数组拆分为多个子数组。
- vsplit等同于使用axis = 0的split（默认值）
- 无论数组尺寸如何，数组始终沿第一个轴拆分。
'''


[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
按索引拆,ar_hsp: [array([[ 1,  2],
       [ 9, 10]]), array([[ 3,  4,  5],
       [11, 12, 13]]), array([[ 6,  7,  8],
       [14, 15, 16]]), array([], shape=(2, 0), dtype=int32)]
按索引拆,len(): 4
按节拆,type(): <class 'list'>
按节拆,len(): 2
按节拆,ar_hsp: [array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]]), array([[ 5,  6,  7,  8],
       [13, 14, 15, 16]])]
按节拆,ar_hsp[0]: [[ 1  2  3  4]
 [ 9 10 11 12]]
------------------------------
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
按索引拆,ar_vsp: [array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]]), array([], shape=(0, 8), dtype=int32), array([], shape=(0, 8), dtype=int32), array([], shape=(0, 8), dtype=int32)]
按索引拆,len(): 4
按节拆,type(): <class 'list'>
按节拆,len(): 2
按节拆,ar_vsp: [array([[1, 2, 3, 4, 5, 6, 7, 8]]), array([[ 9, 10, 11, 12, 13, 14, 15, 16]])]
按节拆,ar_vsp[0]: [[1 2 3 4 5 6 7 8]]


'\nvsplit等同于使用axis = 0的split（默认值），无论数组尺寸如何，数组始终沿第一个轴拆分\n\nar_vsp = np.vsplit(ar,5) # 报错\n\nnumpy.vsplit(ary, indices_or_sections)\n注意点:\n- 数组拆分必须是均分的,否则会报错\n- 垂直（行）将数组拆分为多个子数组。\n- vsplit等同于使用axis = 0的split（默认值）\n- 无论数组尺寸如何，数组始终沿第一个轴拆分。\n'