In [2]:
'''
     Numpy通用函数

    基本操作
'''

'\n     Numpy通用函数\n\n    基本操作\n'

In [17]:
import numpy as np
# 数组形状：.T/.reshape()/.resize()
ar1 = np.arange(10)
print(ar1,ar1.shape)    
print('转置T后:',ar1.T)
    
# 必须保证秩一样
ar2_reshape = ar1.reshape(2,5)  #   用法1：直接将已有数组改变形状
ar3_reshape = np.reshape(ar1, (2,5))  # 用法2：参数内添加数组，目标形状
ar4_reshape = np.zeros((4,6)).reshape(3,8)  # 用法3：生成数组后直接改变形状
print('ar2_reshape  reshape()后:',ar2_reshape)
print('ar3_reshape  reshape()后:',ar3_reshape)
print('ar4_reshape  reshape()后:',ar4_reshape)
                         
ar1_resize = np.resize(ar1, 12)  # 不用保证秩一样 可以大于原来的
ar2_resize = np.resize(ar3_reshape, 5)  # 不用保证秩一样 可以小于原来的
print('ar4_resize resize()后:',ar1_resize)
print('ar3_reshape resize()后:',ar2_resize)    

[0 1 2 3 4 5 6 7 8 9] (10,)
转置T后: [0 1 2 3 4 5 6 7 8 9]
ar2_reshape  reshape()后: [[0 1 2 3 4]
 [5 6 7 8 9]]
ar3_reshape  reshape()后: [[0 1 2 3 4]
 [5 6 7 8 9]]
ar4_reshape  reshape()后: [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
ar4_resize resize()后: [0 1 2 3 4 5 6 7 8 9 0 1]
ar3_reshape resize()后: [0 1 2 3 4]


In [16]:
# 数组的复制
ar1_denghao =  ar1
print(ar1_denghao)
print( ar1_denghao is ar1)
ar1[1] = 9
print(f'等号赋值结果,ar1={ar1},ar1_denghao={ar1_denghao}')
# 回忆python的赋值逻辑：指向内存中生成的一个值 → 这里ar1和ar1_denghao指向同一个值，所以ar1改变，ar1_denghao一起改变
print('------------------')

# .copy()则不同
ar1 = np.arange(10)
ar1_copy = ar1.copy()
print(ar1_copy)
print(ar1_copy is ar1)
ar1[1] = 9
print(f'copy()复制结果,ar1={ar1},ar1_copy={ar1_copy}')  # ar1_copy并未改变

# copy方法生成数组及其数据的完整拷贝
# 提醒：.T/.reshape()/.resize()都是生成新的数组！！！

[0 1 2 3 4 5 6 7 8 9]
True
等号赋值结果,ar1=[0 9 2 3 4 5 6 7 8 9],ar1_denghao=[0 9 2 3 4 5 6 7 8 9]
------------------
[0 1 2 3 4 5 6 7 8 9]
False
copy()复制结果,ar1=[0 9 2 3 4 5 6 7 8 9],ar1_copy=[0 1 2 3 4 5 6 7 8 9]


In [8]:
# 数组类型转换：.astype()
ar1.astype(np.float)


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])