In [3]:
'''
    Numpy索引及切片

    核心：基本索引及切片 / 布尔型索引及切片
'''

'\n    Numpy索引及切片\n\n    核心：基本索引及切片 / 布尔型索引及切片\n'

In [24]:
import numpy as np

# 一维数组:
ar = np.arange(20)
print(ar)
print(ar[4])
print(ar[:3])
print(ar[::2])  # 从头到尾,步长为2

print('二维------------------------')
# 二维数组:
ar = np.arange(16).reshape(4,4)
print(ar)
print(ar[2]) 
print('ar[1][2]):',ar[1][2]) # 同ar[1,2]
print('ar[1,2]):',ar[1,2])
print('ar[:2,2:]',ar[:2,2:])

print('三维-----------------------')
# 三维数组:
ar = np.arange(18).reshape(3,2,3)
print(ar)
print('ar[1]:',ar[1])
print('ar[1][1]:',ar[1][1])
print('ar[1][1][2]:',ar[1][1][2])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
4
[0 1 2]
[ 0  2  4  6  8 10 12 14 16 18]
二维------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 8  9 10 11]
ar[1][2]): 6
ar[1,2]): 6
ar[:2,2:] [[2 3]
 [6 7]]
三维-----------------------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
ar[1]: [[ 6  7  8]
 [ 9 10 11]]
ar[1][1]: [ 9 10 11]
ar[1][1][2]: 11


In [34]:
# 布尔型索引及切片

ar = np.arange(12).reshape(3,4)
print(ar)
i = np.array([True,False,True])
j = np.array([True,True,False,False])
print('i:',i)
print('j:',j)

print('ar[i,:]:',ar[i,:])  # 在第一维度做判断，只保留True，这里第一维度就是行，ar[i,:] = ar[i]（简单书写格式）
print('ar[:,j:',ar[:,j])  # 在第二维度做判断，这里如果ar[:,i]会有警告，因为i是3个元素，而ar在列上有4个
# 布尔型索引：以布尔型的矩阵去做筛选

m = ar > 5
print(m)  # 这里m是一个判断矩阵  布尔型数组
print(ar[m])  # 用m判断矩阵去筛选ar数组中>5的元素 → 重点！后面的pandas判断方式原理就来自此处


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
i: [ True False  True]
j: [ True  True False False]
ar[i,:]: [[ 0  1  2  3]
 [ 8  9 10 11]]
ar[:,j: [[0 1]
 [4 5]
 [8 9]]
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11]


In [33]:
# 数组索引及切片的值更改、复制

ar = np.arange(10)
print(ar)
ar[5] = 100
ar[7:9] = 200
print(ar)
# 一个标量赋值给一个索引/切片时，会自动改变/传播原始数组

ar = np.arange(10)
b = ar.copy()
b[7:9] = 200
print(ar)
print(b)
# 复制


[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3   4 100   6 200 200   9]
[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3   4   5   6 200 200   9]
