In [1]:
'''  
    Numpy数据的输入输出
    
    numpy读取/写入数组数据、文本数据
'''

'  \n    Numpy数据的输入输出\n    \n    numpy读取/写入数组数据、文本数据\n'

In [7]:
import numpy as np
import os 

# 存储数组数据 .npy文件

# chdir() 将当前工作目录更改为指定的路径
os.chdir("F:/ATest_ignore")  
ar = np.random.randint(1,10,size=(2,3))
print(ar)

# save() 将数组保存为NumPy .npy格式的二进制文件
np.save('arraydata1.npy',ar)  

# load() 读取数组数据.npy文件  
ar_load = np.load('arraydata1.npy')  
print(ar_load)

[[1 7 1]
 [2 9 4]]
[[1 7 1]
 [2 9 4]]


In [11]:
# 存储/读取文本文件
ar = np.random.rand(4,5)
print(ar)

# savetxt() 将数组保存到文本文件。源码如下:
# def savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='',
#             footer='', comments='# ', encoding=None):
np.savetxt('arraydata2.txt',ar,fmt='%.2f',delimiter=',')   # 保存小数点后两位,并且以','分割


# loadtxt() 从文本文件加载数据。文本文件中的每一行必须具有相同数量的值。
'''
def loadtxt(fname, dtype=float, comments='#', delimiter=None,
            converters=None, skiprows=0, usecols=None, unpack=False,
           ndmin=0, encoding='bytes', max_rows=None):
'''
ar_loadtxt = np.loadtxt('arraydata2.txt', delimiter=',')
print(ar_loadtxt)


[[0.79067832 0.32378    0.4422647  0.62181106 0.80300266]
 [0.87556629 0.11427465 0.53967467 0.55447063 0.16374469]
 [0.93433415 0.68061453 0.59362985 0.62311052 0.59708388]
 [0.13524089 0.25351945 0.43554054 0.59086958 0.41731343]]
[[0.79 0.32 0.44 0.62 0.8 ]
 [0.88 0.11 0.54 0.55 0.16]
 [0.93 0.68 0.59 0.62 0.6 ]
 [0.14 0.25 0.44 0.59 0.42]]
